Parameters:
  VpcId:
    Type: String
  Subnet1:
    Type: String
  Subnet2:
    Type: String
  SecurityGroup:
    Type: String
  ImageUri:
    Type: String

Resources:
  Cluster:
    Type: AWS::ECS::Cluster

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/express-api
      RetentionInDays: 7  # keep logs for 7 days

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: express-task
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: arn:aws:iam::864981759262:role/ecsTaskExecutionRole
      ContainerDefinitions:
        - Name: express-container
          Image: !Ref ImageUri
          PortMappings:
            - ContainerPort: 3000
          Environment:
            - Name: PORT
              Value: "3000"
          LogConfiguration:                # ✅ CloudWatch logs enabled
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: express-alb
      Scheme: internet-facing
      Subnets:
        - !Ref Subnet1
        - !Ref Subnet2
      SecurityGroups:
        - !Ref SecurityGroup

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: express-tg
      Port: 3000
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VpcId
      HealthCheckPath: /health
      HealthCheckIntervalSeconds: 30
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 5
      Matcher:
        HttpCode: 200

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      DesiredCount: 1
      LaunchType: FARGATE
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref Subnet1
            - !Ref Subnet2
          SecurityGroups:
            - !Ref SecurityGroup
      TaskDefinition: !Ref TaskDefinition
      LoadBalancers:
        - TargetGroupArn: !Ref TargetGroup
          ContainerName: express-container
          ContainerPort: 3000

Outputs:
  LoadBalancerDNSName:
    Description: Public URL of the load balancer
    Value: !GetAtt LoadBalancer.DNSName
  CloudWatchLogGroup:
    Description: Log group for ECS container logs
    Value: !Ref LogGroup
